import type { MarketApp } from "./sample-apps";

type Concept = Omit<MarketApp, "symbol" | "price" | "trial"> & { trial?: string };
function app(concept: Concept): MarketApp {
  return { ...concept, symbol: concept.name.slice(0, 2).toUpperCase(), price: `From ${concept.plans?.[0].price}`, trial: concept.trial ?? "14-day trial" };
}

export const additionalSampleApps: MarketApp[] = [
  app({ id: "salon-chat", name: "Salon Chat", category: "Customer care", color: "mint", publisher: "Hellochair",
    summary: "One friendly inbox for customer questions and team handoffs.",
    description: "Keep appointment questions out of scattered personal messages. A proposed salon inbox brings website conversations together, lets staff assign a thread and helps customers find their next booking. Customer-facing chat and internal notes stay separate.",
    features: ["Website chat widget", "Shared customer inbox", "Private team notes"], permissions: ["Read customer names and appointment context", "Read and send salon chat messages"],
    workflow: ["Add a chat widget to your salon website", "Assign incoming conversations to your team", "Reply with a service or booking link"],
    plans: [{ name: "Starter", price: "$15 / month", detail: "Per salon · 2 team seats, 500 new conversations monthly and saved replies." }, { name: "Team", price: "$29 / month", detail: "Per salon · 10 seats, 2,000 new conversations monthly and assignment rules." }],
  }),
  app({ id: "sms-connect", name: "SMS Connect", category: "Customer care", color: "blue", publisher: "Pingpath",
    summary: "Timely texts for appointments, updates and a thoughtful follow-up.",
    description: "Prepare reminders and appointment updates with clear delivery history. Customers can opt out, and the salon can separate operational reminders from promotional campaigns. Messaging availability would depend on sender registration and destination.",
    features: ["Reminder templates", "Opt-out controls", "Delivery history"], permissions: ["Read appointment times and customer phone numbers", "Read communication consent and send approved SMS"],
    workflow: ["Set up a salon sender and customer preferences", "Choose reminder timing and message templates", "Review usage and delivery outcomes"],
    plans: [{ name: "Connect", price: "$9 / month", detail: "Per salon · Templates and delivery logs; example US SMS usage $0.03 per segment, charged separately." }, { name: "Automate", price: "$25 / month", detail: "Per salon · Scheduled workflows and team inbox; SMS, carrier and sender-registration fees are additional." }],
  }),
  app({ id: "merchant-rate", name: "Merchant Rate Match", category: "Payments", color: "peach", publisher: "Fairlane Pay", trial: "Free statement review concept",
    summary: "Understand your processing costs and explore a better-fit offer.",
    description: "Turn a merchant statement into a clear comparison of processing fees, terminal costs and contract terms. This concept would help a salon request provider quotes; lower rates are not guaranteed. Quotes depend on volume, card mix, risk review and provider approval.",
    features: ["Statement fee breakdown", "Provider quote comparison", "Contract and hardware checklist"], permissions: ["Read aggregate payment volume", "Access merchant statements uploaded for review"],
    workflow: ["Upload a statement with sensitive account details removed", "Review your effective costs and contract terms", "Request and compare an itemized provider quote"],
    plans: [{ name: "Compare", price: "$0", detail: "Example one-time statement review. No processor switch or payment collection in this preview." }, { name: "Monitor", price: "$19 / month", detail: "Per salon · Monthly fee tracking. Processing, hardware and provider charges are quoted separately." }],
  }),
  app({ id: "auto-backup", name: "Auto Backup", category: "Operations", color: "blue", publisher: "Vaultnest",
    summary: "Scheduled business exports, with a restore plan you can review.",
    description: "Keep an independent copy of supported salon records on a schedule. A proposed encrypted export vault would show what was saved, when it was captured and which records can be restored. This is a business-data export concept, not a complete database or payment-card backup.",
    features: ["Scheduled encrypted exports", "Retention settings", "Restore preview"], permissions: ["Read selected salon business records", "Create export archives and restore owner-approved records"],
    workflow: ["Choose supported records and a retention window", "Schedule an export and review its status", "Preview a restore before approving changes"],
    plans: [{ name: "Daily", price: "$9 / month", detail: "Per salon · Daily exports, 30-day retention and up to 5 GB of archive storage." }, { name: "Protect", price: "$19 / month", detail: "Per salon · 90-day retention and 25 GB. Restores cover supported records only." }],
  }),
  app({ id: "tax-company", name: "Tax Company Connect", category: "Payroll", color: "sand", publisher: "Ledgerbridge", trial: "Free consultation request concept",
    summary: "Bring organized salon records to your chosen tax professional.",
    description: "Prepare a year-end handoff with payroll summaries, sales exports and a checklist of missing documents. Invite your chosen tax company to review a scoped package. Filing, advice and representation would require a separate engagement with the professional; no tax outcome is promised.",
    features: ["Year-end document checklist", "Accountant export package", "Scoped advisor sharing"], permissions: ["Read owner-selected payroll and financial summaries", "Share approved exports with an invited advisor"],
    workflow: ["Choose the year and documents to include", "Review missing items and approve the package", "Share with your tax professional for a separate engagement"],
    plans: [{ name: "Handoff", price: "$49 / year", detail: "Per salon · One annual export package and document checklist. Professional fees excluded." }, { name: "Advisor workspace", price: "$15 / month", detail: "Per salon · Ongoing document sharing and quarterly packages. Tax preparation and filing quoted separately." }],
  }),
  app({ id: "custom-payroll", name: "Custom Payroll", category: "Payroll", color: "lavender", publisher: "Paycraft",
    summary: "Shape payroll rules around the way your salon team works.",
    description: "Model hourly pay, service commission, bonuses and tip allocations in a reviewable rule builder. Compare a draft with the previous period before the owner approves it. Rule configuration would not replace payroll compliance review, tax filing or wage payment services.",
    features: ["Commission rule builder", "Tip allocation scenarios", "Draft payroll comparison"], permissions: ["Read staff earnings and payroll inputs", "Create payroll drafts and owner-approved rule changes"],
    workflow: ["Choose pay rules for each eligible staff group", "Preview a period and inspect exceptions", "Approve a draft for your payroll workflow"],
    plans: [{ name: "Studio", price: "$29 / month", detail: "Per salon · Up to 15 staff, pay-rule templates and draft comparisons." }, { name: "Advanced", price: "$59 / month", detail: "Per salon · Up to 50 staff, custom rule groups and approval history. Filing and disbursement excluded." }],
  }),
  app({ id: "facebook-connect", name: "Facebook Connection", category: "Marketing", color: "blue", publisher: "Socialthread",
    summary: "Plan your salon’s Facebook presence from one workspace.",
    description: "Draft posts around salon services and link customers back to booking. The proposed connection uses a salon-authorized Facebook Page and would depend on Meta permissions and app review. It is an independent concept, not a Meta product or endorsed integration.",
    features: ["Page post drafts", "Booking-link campaigns", "Publishing calendar"], permissions: ["Read approved salon profile content", "Access and publish to an authorized Facebook Page"],
    workflow: ["Connect a Page you are authorized to manage", "Prepare a post with approved photos and a booking link", "Review and schedule the post"],
    plans: [{ name: "Page", price: "$12 / month", detail: "Per salon · One Page, 30 scheduled posts monthly and a content calendar." }, { name: "Studio", price: "$25 / month", detail: "Per salon · Three Pages and approval workflows. Advertising spend and third-party charges excluded." }],
  }),
  app({ id: "ai-marketing", name: "AI Marketing Studio", category: "Marketing", color: "rose", publisher: "Musebloom",
    summary: "From a quiet-week idea to a campaign your team can approve.",
    description: "Give the assistant a service, an audience and your salon’s tone. Explore caption drafts, campaign outlines and seasonal ideas, then edit before publishing. AI content can be inaccurate; the salon controls approval, and audience data would be minimized. Bookings and revenue are not guaranteed.",
    features: ["Caption and campaign drafts", "Brand tone presets", "Human approval workflow"], permissions: ["Read selected public salon content and service descriptions", "Create marketing drafts using approved campaign inputs"],
    workflow: ["Choose a service, campaign goal and salon tone", "Generate and edit a set of draft ideas", "Approve content for your connected channels"],
    plans: [{ name: "Spark", price: "$19 / month", detail: "Per salon · 100 text generations monthly, tone presets and campaign drafts." }, { name: "Studio", price: "$49 / month", detail: "Per salon · 500 text generations and team approvals. Message delivery and ad spend excluded." }],
  }),
  app({ id: "qr-ticket", name: "QR Ticket", category: "Operations", color: "mint", publisher: "Scanlane",
    summary: "A simple scan from the front desk to the right ticket.",
    description: "Create a short-lived QR link for a ticket or receipt. Customer links show only the information intended for that customer; staff actions would still require an authorized session. QR labels make a busy front-desk handoff easier without putting private data inside the code.",
    features: ["Ticket QR labels", "Customer receipt links", "Link expiry controls"], permissions: ["Read selected ticket and receipt details", "Create scoped ticket links"],
    workflow: ["Choose a ticket or receipt", "Generate a scoped QR link with an expiry", "Scan to open the permitted view"],
    plans: [{ name: "Basic", price: "$0", detail: "Per salon · Up to 100 QR links monthly with standard branding." }, { name: "Desk", price: "$8 / month", detail: "Per salon · Up to 2,000 links, branded print layouts and configurable expiry." }],
  }),
  app({ id: "customer-import", name: "Import Customer Data", category: "Customer care", color: "peach", publisher: "Welcomeport",
    summary: "Bring your customer list over with a careful, guided preview.",
    description: "Map CSV columns, normalize phone numbers and inspect likely duplicates before importing. Invalid rows get a clear report, and the salon approves the final batch. Importing a contact would not automatically grant marketing consent or transfer sensitive payment information.",
    features: ["CSV column mapping", "Duplicate review", "Import error report"], permissions: ["Read customer matching fields", "Create and update approved customer records"],
    workflow: ["Upload a CSV and map customer fields", "Review duplicates, consent fields and invalid rows", "Approve the batch and download the results"],
    plans: [{ name: "One-time", price: "$19 / import", detail: "Per batch · Up to 5,000 rows, mapping preview and error report." }, { name: "Migration", price: "$49 / import", detail: "Per batch · Up to 25,000 rows and reusable mappings. No automatic merge without review." }], trial: "Free mapping preview",
  }),
  app({ id: "gift-card", name: "Gift Card Studio", category: "Commerce", color: "rose", publisher: "Giftpetal",
    summary: "Make a salon visit a gift, with balances your team can follow.",
    description: "Design digital gift cards, choose preset amounts and track redemption in a clear balance ledger. The proposed flow connects purchases to an approved payment provider and lets owners review adjustments. Gift-card terms and refund policies remain salon-controlled.",
    features: ["Branded digital gift cards", "Balance and redemption ledger", "Scheduled gift delivery"], permissions: ["Read and create gift-card records", "Record authorized redemptions and payment references"],
    workflow: ["Set gift amounts, designs and salon terms", "Preview purchase and delivery through a payment provider", "Redeem a card and review its remaining balance"],
    plans: [{ name: "Gift", price: "$15 / month", detail: "Per salon · Up to 200 gift cards issued monthly and standard designs." }, { name: "Occasion", price: "$29 / month", detail: "Per salon · Up to 1,000 cards and custom designs. Payment-processing fees excluded." }],
  }),
  app({ id: "membership", name: "Salon Membership", category: "Commerce", color: "lavender", publisher: "Clubchair",
    summary: "Turn regular visits into a plan customers can understand.",
    description: "Build a membership with clearly defined service credits, benefits and renewal terms. Let customers see what they have left and let staff review eligibility before redemption. Recurring charges would require explicit customer consent and a compatible billing provider.",
    features: ["Membership plan builder", "Service credit tracking", "Renewal and cancellation controls"], permissions: ["Read customer and service eligibility", "Manage membership records and approved billing references"],
    workflow: ["Define benefits, renewal terms and cancellation rules", "Enroll a customer with explicit approval", "Track credits, renewals and redemptions"],
    plans: [{ name: "Club", price: "$25 / month", detail: "Per salon · Three membership plans and up to 200 active members." }, { name: "Club Plus", price: "$49 / month", detail: "Per salon · Ten plans and up to 1,000 members. Payment-provider and recurring billing fees excluded." }],
  }),
  app({ id: "rewards", name: "Rewards Circle", category: "Customer care", color: "sand", publisher: "Perkcircle",
    summary: "Give loyal customers a clear path to their next little perk.",
    description: "Choose how eligible visits or purchases earn points and what those points unlock. A visible ledger helps staff explain balances, reversals and redemptions. Reward value, expiry and qualifying purchases would follow the salon’s published program rules.",
    features: ["Points and visit stamps", "Reward catalog", "Adjustment history"], permissions: ["Read eligible completed visits and purchase totals", "Manage reward points and approved redemptions"],
    workflow: ["Set earning rules and reward terms", "Preview points on an eligible completed visit", "Redeem a reward and record the balance change"],
    plans: [{ name: "Circle", price: "$15 / month", detail: "Per salon · Up to 500 enrolled customers, points and visit stamps." }, { name: "Circle Plus", price: "$29 / month", detail: "Per salon · Up to 2,500 enrolled customers, tiered perks and scheduled summaries." }],
  }),
  app({ id: "website-layout", name: "Website Layout Studio", category: "Commerce", color: "sand", publisher: "Canvaschair",
    summary: "A salon website that feels like your brand, from the first tap.",
    description: "Choose a layout, arrange services and galleries, and preview the result on mobile before publishing. Proposed templates use approved salon content and connect to Reylumi booking. Custom domains would require ownership verification and separate domain registration.",
    features: ["Salon layout collection", "Mobile design preview", "Booking-linked sections"], permissions: ["Read approved public salon content", "Save and publish owner-approved website layout settings"],
    workflow: ["Pick a layout and your salon colors", "Arrange services, photos and booking links", "Preview mobile and desktop, then approve publishing"],
    plans: [{ name: "Essential", price: "$12 / month", detail: "Per salon · Five layouts and a proposed hosted salon subdomain." }, { name: "Signature", price: "$29 / month", detail: "Per salon · Fifteen layouts and custom-domain connection. Domain registration sold separately." }],
  }),
  app({ id: "online-store", name: "Salon Online Store", category: "Commerce", color: "mint", publisher: "Shelfside",
    summary: "Bring your retail shelf online, with local pickup built in.",
    description: "Publish selected retail products with prices and available stock, then offer a simple pickup checkout. Orders would connect to salon inventory and an approved payment provider. Shipping integrations would be a later option rather than an implied included service.",
    features: ["Retail product storefront", "Salon pickup orders", "Stock-aware checkout"], permissions: ["Read and publish approved product listings", "Create store orders and reserve inventory"],
    workflow: ["Choose products, photos and pickup hours", "Preview checkout and payment-provider settings", "Review an order and prepare it for pickup"],
    plans: [{ name: "Shelf", price: "$29 / month", detail: "Per salon · Up to 100 products and 200 pickup orders monthly." }, { name: "Store", price: "$59 / month", detail: "Per salon · Up to 1,000 products and 1,000 pickup orders monthly. Processing and shipping charges excluded." }],
  }),
  app({ id: "promotion", name: "Promotion Builder", category: "Marketing", color: "peach", publisher: "Offerloom",
    summary: "Create an offer that is easy to explain and simple to redeem.",
    description: "Prepare a seasonal offer, a service bundle or a limited coupon with transparent eligibility. Preview the price impact before activating it, then follow redemptions against your chosen limit. Discounts would respect salon rules and could not stack unless explicitly allowed.",
    features: ["Coupon and bundle builder", "Eligibility and date controls", "Redemption tracking"], permissions: ["Read service and product pricing", "Manage owner-approved promotions and redemption records"],
    workflow: ["Choose an offer, eligible items and active dates", "Preview discount limits and stacking rules", "Approve the offer and review redemptions"],
    plans: [{ name: "Launch", price: "$12 / month", detail: "Per salon · Five active promotions, coupon codes and redemption limits." }, { name: "Campaign", price: "$25 / month", detail: "Per salon · Twenty active promotions, bundles and reporting. SMS and advertising spend excluded." }],
  }),
];
