import { notFound } from "next/navigation";
import Link from "next/link";
import { requirePlatformAdmin } from "@/lib/platform-admin/auth";
import { PLATFORM_ADMIN_PERMISSIONS as P } from "@/lib/platform-admin/permissions";
import { getSupportEmailConfig, publicSupportEmailConfig } from "@/lib/support-email";
import { AdminPageHeader, AdminSection } from "../../_components/admin-ui";
import { AdminActionForm } from "../../_components/action-form";
import { saveSupportEmailSettingsAction } from "./actions";

export default async function SupportEmailSettingsPage() {
  const actor = await requirePlatformAdmin(P.teamManage);
  if (actor.roleSlug !== "platform_owner") notFound();
  const safe = publicSupportEmailConfig(await getSupportEmailConfig());
  return <><AdminPageHeader eyebrow="Integration" title="Support email">Connect a verified sender so admins can email customers directly from Inbox.</AdminPageHeader><Link href="/admin/settings" className="mt-4 inline-block text-sm text-orange-700">Back to settings →</Link><AdminSection title="Sender connection"><div className="max-w-2xl rounded-xl border border-zinc-200 bg-white p-6"><p className="mb-5 text-sm text-zinc-500">Provider: Resend · {safe.keyConfigured && safe.enabled ? "Connected configuration" : "Not connected"}. The key is encrypted and is never displayed again after saving.</p><AdminActionForm action={saveSupportEmailSettingsAction} className="grid gap-5"><label className="grid gap-1.5 text-sm font-medium">Support email address<input name="from" required type="email" maxLength={254} defaultValue={safe.from} className="rounded-lg border border-zinc-300 px-3 py-2" /></label><label className="grid gap-1.5 text-sm font-medium">Resend API key<input name="api_key" type="password" autoComplete="new-password" maxLength={200} placeholder={safe.keyConfigured ? "Leave blank to keep the saved key" : "Enter your Resend API key"} className="rounded-lg border border-zinc-300 px-3 py-2" /><span className="text-xs font-normal text-zinc-500">The key needs access to send email and check the verified sender domain.</span></label><label className="flex items-center gap-2 text-sm"><input name="enabled" type="checkbox" defaultChecked={safe.enabled && safe.keyConfigured} />Enable direct support email replies</label><div className="flex flex-wrap gap-3"><button name="intent" value="save" className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save connection</button><button name="intent" value="test" className="rounded-lg border border-zinc-200 bg-white px-4 py-2 text-sm font-medium">Check connection</button></div></AdminActionForm></div></AdminSection><AdminSection title="Before connecting"><ol className="max-w-2xl list-decimal space-y-3 pl-5 text-sm leading-relaxed text-zinc-600"><li>Add and verify <strong>reylumi.com</strong> in your <a href="https://resend.com/domains" target="_blank" rel="noreferrer" className="text-orange-700 underline">Resend account</a>.</li><li>Use a key with sending and domain access. The connection check does not send a test email.</li><li>Make sure <strong>support@reylumi.com</strong> is a working mailbox if customers should reply by email. This connection enables sending; it does not create the mailbox.</li></ol><p className="mt-5 text-sm text-zinc-500">Website form messages arrive in Inbox even when direct email is disabled. Customer email replies are received in your support mailbox.</p></AdminSection></>;
}
