-- Fixtures and all assertions must run inside a transaction which is rolled back.
do $$
declare salon uuid; account uuid; customer uuid; service uuid; staff1 uuid; staff2 uuid; key uuid; signature text;
 starts timestamptz; result1 jsonb; result2 jsonb; rejected boolean; slot_data jsonb; n integer;
 operation uuid:=gen_random_uuid(); payload jsonb; replayed jsonb;
begin
 insert into accounts(name) values('Scheduler test fixture') returning id into account;
 insert into locations(account_id,name) values(account,'Scheduler test fixture') returning id into salon;
 insert into booking_settings(salon_id,timezone_iana,confirmation_mode,default_cleanup_buffer_minutes) values(salon,'America/Chicago','request_confirmation',15);
 insert into customers(location_id,name,email,phone) values(salon,'Test customer','fixture@example.invalid','+15555550123') returning id into customer;
 insert into services(salon_id,name,duration_minutes) values(salon,'Fixture service',30) returning id into service;
 insert into staff(salon_id,display_name) values(salon,'Fixture A') returning id into staff1;
 insert into staff(salon_id,display_name) values(salon,'Fixture B') returning id into staff2;
 insert into staff_service_assignments(salon_id,staff_id,service_id,custom_duration_minutes) values(salon,staff1,service,45),(salon,staff2,service,45);
 starts := (((statement_timestamp() at time zone 'America/Chicago')::date+3)+time '09:00') at time zone 'America/Chicago';
 insert into staff_availability_rules(salon_id,day_of_week,starts_at_local,ends_at_local) values(salon,extract(dow from starts at time zone 'America/Chicago'), '08:00','18:00');
 insert into pos_portable_access_keys(salon_id,access_id,passcode_salt,passcode_digest,capabilities)
 values(salon,gen_random_uuid()::text,'fixture','fixture',array['portable.book.view','portable.book.create']) returning id into key;
 signature:=pos_portable_access_signature(key,'fixture');
 result1:=create_pos_portable_appointment_v2(key,signature,'Test customer',null,'fixture@example.invalid',service,null,starts,customer);
 if result1->>'status'<>'pending' then raise exception 'Confirmation setting ignored'; end if;
 if (result1->>'endAt')::timestamptz<>starts+interval '60 minutes' then raise exception 'Custom duration or buffer ignored'; end if;
 if (result1->>'customerId')::uuid<>customer then raise exception 'Customer identity lost'; end if;
 result2:=create_pos_portable_appointment_v2(key,signature,'Test customer',null,'fixture@example.invalid',service,null,starts+interval '2 hours',customer);
 if result1->>'staffId'=result2->>'staffId' then raise exception 'Fair rotation failed'; end if;
 rejected:=false;
 begin update booking_staff_reservations set staff_id=(result1->>'staffId')::uuid,occupied=tstzrange(starts,starts+interval '1 hour','[)')
   where line_id in(select id from booking_lines where booking_id=(result2->>'id')::uuid);
 exception when exclusion_violation then rejected:=true; end;
 if not rejected then raise exception 'Atomic overlap constraint failed'; end if;
 rejected:=false;
 begin perform create_pos_portable_appointment_v2(key,signature,'Test',null,null,service,(result1->>'staffId')::uuid,starts+interval '45 minutes',customer);
 exception when others then if sqlerrm not like '%No available%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Buffer overlap accepted'; end if;
 rejected:=false;
 begin perform create_pos_portable_appointment_v2(key,signature,'Test',null,null,service,staff1,starts-interval '2 hours',customer);
 exception when others then if sqlerrm not like '%No available%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Outside working hours accepted'; end if;
 insert into staff_time_blocks(salon_id,staff_id,block_type,starts_at,ends_at) values(salon,staff1,'time_off',starts+interval '4 hours',starts+interval '5 hours');
 if booking_staff_available(salon,staff1,service,starts+interval '4 hours',starts+interval '5 hours') then raise exception 'Time off ignored'; end if;
 update staff_service_assignments set is_active=false where staff_id=staff2;
 if booking_staff_available(salon,staff2,service,starts+interval '4 hours',starts+interval '5 hours') then raise exception 'Service eligibility ignored'; end if;
 update staff_service_assignments set is_active=true where staff_id=staff2;
 slot_data:=get_pos_portable_booking_slots(key,signature,service,(result1->>'staffId')::uuid,(starts at time zone 'America/Chicago')::date);
 if exists(select 1 from jsonb_array_elements(slot_data) x where x->>'label'='09:45') then raise exception 'Busy slot advertised'; end if;
 update bookings set status='cancelled' where id=(result1->>'id')::uuid;
 if not booking_staff_available(salon,(result1->>'staffId')::uuid,service,starts,starts+interval '1 hour') then raise exception 'Cancellation did not free schedule'; end if;
 select count(*) into n from booking_message_outbox where booking_id=(result1->>'id')::uuid and channel='email';
 if n<>2 then raise exception 'Notification event dedupe failed: %',n; end if;
 update bookings set status='cancelled' where id=(result1->>'id')::uuid;
 if (select count(*) from booking_message_outbox where booking_id=(result1->>'id')::uuid and channel='email')<>2 then raise exception 'Duplicate cancellation message'; end if;
 rejected:=false;
 begin perform create_pos_portable_appointment_v2(key,signature,'Test',null,null,service,staff1,starts,gen_random_uuid());
 exception when others then if sqlerrm not like '%Selected customer%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Foreign customer identity accepted'; end if;
 update booking_settings set confirmation_mode='instant_booking' where salon_id=salon;
 payload:=jsonb_build_object('customerId',customer,'customerName','Test','serviceId',service,'startAt',starts+interval '7 hours');
 result2:=replay_pos_portable_operation(key,signature,operation,'booking',statement_timestamp(),payload);
 replayed:=replay_pos_portable_operation(key,signature,operation,'booking',statement_timestamp(),payload);
 if result2->>'id'<>replayed->>'id' then raise exception 'Retry duplicated appointment'; end if;
 if result2->>'status'<>'confirmed' then raise exception 'Instant confirmation ignored'; end if;
 perform get_pos_portable_book_data(key,signature,(starts at time zone 'America/Chicago')::date);
 if (get_pos_portable_access_context(key,signature)->>'touch_keyboard_enabled')::boolean is not true then raise exception 'Touch keyboard default missing'; end if;
 perform claim_booking_messages(50,false,false);
 if exists(select 1 from booking_message_outbox where salon_id=salon and state='sending') then raise exception 'Unconfigured channel was claimed'; end if;
 if has_function_privilege('anon','public.claim_booking_messages(integer,boolean,boolean)','execute') then raise exception 'Public message worker access'; end if;
 rejected:=false;
 begin update bookings set status='no_show' where id=(result2->>'id')::uuid;
 exception when others then if sqlerrm not like '%before its scheduled start%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Future no-show accepted'; end if;
 update bookings set customer_cancellation_token_hash='fixture-token' where id=(result2->>'id')::uuid;
 update bookings set cancellation_policy_snapshot=jsonb_build_object('cancellationWindowMinutes',10080) where id=(result2->>'id')::uuid;
 if cancel_public_booking_by_manage_token('fixture-token')->>'code'<>'cancellation_window_closed' then raise exception 'Cancellation deadline ignored'; end if;
end; $$;
