begin;
-- Historical fixture inserts bypass only the creation-time policy, not lifecycle validation.
alter table public.bookings disable trigger enforce_booking_time_policy;
do $test$
declare a uuid; s uuid; other_s uuid; c uuid; other_c uuid; svc uuid; k uuid; readonly_key uuid; sig text; readonly_sig text;
 b uuid; next_b uuid; legacy uuid; staff_b uuid; assigned_staff uuid; v timestamptz; result jsonb; history jsonb; rejected boolean; u uuid:=gen_random_uuid(); pub uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email) values(u,'no-show-'||u||'@example.invalid');
 insert into public.users(id,auth_user_id,email,display_name) values(pub,u,'no-show-'||u||'@example.invalid','No-show QA');
 insert into accounts(name,status) values('No-show QA','active') returning id into a;
 insert into locations(account_id,name,status,country) values(a,'No-show QA','active','US') returning id into s;
 insert into locations(account_id,name,status,country) values(a,'Other salon','active','US') returning id into other_s;
 insert into roles(account_id,name,code,is_system) values(a,'Owner','OWNER',true) on conflict(account_id,code) do nothing;
 insert into account_memberships(account_id,user_id,role_id,status) values(a,pub,(select id from roles where account_id=a and code='OWNER'),'active');
 insert into booking_settings(salon_id,timezone_iana) values(s,'America/Chicago'),(other_s,'America/Chicago');
 insert into customers(location_id,name) values(s,'QA customer') returning id into c;
 insert into customers(location_id,name) values(s,'Different customer') returning id into other_c;
 insert into services(salon_id,name,duration_minutes,base_price) values(s,'Manicure',30,40) returning id into svc;
 insert into pos_portable_access_keys(salon_id,access_id,passcode_salt,passcode_digest,capabilities)
 values(s,gen_random_uuid()::text,'fixture','fixture',array['portable.book.view','portable.book.create','portable.book.cancel']) returning id into k;
 insert into pos_portable_access_keys(salon_id,access_id,passcode_salt,passcode_digest,capabilities)
 values(s,gen_random_uuid()::text,'fixture','fixture',array['portable.book.view']) returning id into readonly_key;
 sig:=pos_portable_access_signature(k,'fixture'); readonly_sig:=pos_portable_access_signature(readonly_key,'fixture');
 insert into bookings(salon_id,customer_id,start_at,end_at,status,confirmation_status) values(s,c,now()-interval '2 days',now()-interval '2 days'+interval '30 minutes','confirmed','confirmed') returning id,updated_at into b,v;
 insert into booking_lines(salon_id,booking_id,service_id,service_name_snapshot,duration_minutes,unit_price,line_total) values(s,b,svc,'Manicure',30,40,40);
 result:=manage_pos_portable_booking(k,sig,b,'mark_no_show',jsonb_build_object('updatedAt',v));
 if result->>'noShowKind'<>'unexcused' or result->>'status'<>'no_show' then raise exception 'One-click unexcused no-show failed'; end if;
 if (select no_show_reason from bookings where id=b) is not null then raise exception 'Note was required or invented'; end if;
 insert into bookings(salon_id,customer_id,start_at,end_at,status,confirmation_status) values(s,c,now()+interval '2 days',now()+interval '2 days 30 minutes','pending','requested') returning id,updated_at into next_b,v;
 result:=manage_pos_portable_booking(k,sig,next_b,'confirm',jsonb_build_object('updatedAt',v));
 if result->>'requiresNoShowReview'<>'true' or jsonb_array_length(result->'noShowHistory')<>1 then raise exception 'Warning missing'; end if;
 if (select status from bookings where id=next_b)<>'pending' then raise exception 'Warning already confirmed appointment'; end if;
 if result->'noShowHistory'->0->'services'->>0<>'Manicure' then raise exception 'Service history missing'; end if;
 result:=manage_pos_portable_booking(k,sig,next_b,'confirm',jsonb_build_object('updatedAt',v,'acknowledgeNoShow',true));
 if result->>'status'<>'confirmed' then raise exception 'Confirm anyway failed'; end if;
 rejected:=false;
 begin perform manage_pos_portable_booking(k,sig,next_b,'mark_no_show',jsonb_build_object('updatedAt',result->>'updatedAt'));
 exception when others then if sqlerrm not like '%before its scheduled start%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Future no-show accepted'; end if;
 select updated_at into v from bookings where id=b;
 rejected:=false;
 begin perform manage_pos_portable_booking(readonly_key,readonly_sig,b,'mark_no_show_excused',jsonb_build_object('updatedAt',v));
 exception when others then if sqlerrm not like '%cannot mark no-show%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Read-only device changed no-show'; end if;
 result:=manage_pos_portable_booking(k,sig,b,'mark_no_show_excused',jsonb_build_object('updatedAt',v,'reason','Customer called'));
 if result->>'noShowKind'<>'excused' then raise exception 'Reclassification failed'; end if;
 if jsonb_array_length(booking_no_show_history(s,next_b))<>0 then raise exception 'Excused counted in warning'; end if;
 select updated_at into v from bookings where id=b;
 rejected:=false;
 begin perform manage_pos_portable_booking(k,sig,b,'mark_no_show',jsonb_build_object('updatedAt',v-interval '1 minute'));
 exception when others then if sqlerrm not like '%changed on another device%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Stale classification accepted'; end if;
 perform set_config('request.jwt.claim.sub',u::text,true);
 perform save_pos_workspace_booking(b,v,jsonb_build_object('command','mark_no_show'));
 if (select no_show_kind from bookings where id=b)<>'unexcused' then raise exception 'Owner reclassification failed'; end if;
 if (select no_show_reason from bookings where id=b)<>'Customer called' then raise exception 'Blank optional note removed history'; end if;
 insert into bookings(salon_id,customer_id,start_at,end_at,status,confirmation_status) values(s,c,now()+interval '3 days',now()+interval '3 days 30 minutes','pending','requested') returning id,updated_at into next_b,v;
 rejected:=false;
 begin perform save_pos_workspace_booking(next_b,v,jsonb_build_object('command','confirm'));
 exception when others then if sqlerrm not like '%Review this customer%' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Owner bypassed warning'; end if;
 perform save_pos_workspace_booking(next_b,v,jsonb_build_object('command','confirm','acknowledge_no_show',true));
 insert into bookings(salon_id,customer_id,start_at,end_at,status) values(s,c,now()-interval '5 days',now()-interval '5 days'+interval '30 minutes','no_show') returning id into legacy;
 update bookings set no_show_reason='Old note' where id=legacy;
 if jsonb_array_length(booking_no_show_history(s,next_b))<>1 then raise exception 'Legacy note inferred classification'; end if;
 insert into bookings(salon_id,customer_id,start_at,end_at,status,no_show_kind) values(other_s,c,now()-interval '6 days',now()-interval '6 days'+interval '30 minutes','no_show','unexcused');
 insert into bookings(salon_id,customer_id,start_at,end_at,status,no_show_kind) values(s,other_c,now()-interval '7 days',now()-interval '7 days'+interval '30 minutes','no_show','unexcused');
 if jsonb_array_length(get_booking_no_show_history(next_b))<>1 then raise exception 'Other salon/customer history leaked'; end if;
 if (get_booking_no_show_counts(array[next_b])->>next_b::text)::integer<>1 then raise exception 'Badge count wrong'; end if;
 result:=get_pos_portable_book_data(k,sig,(now()-interval '2 days')::date);
 if not exists(select 1 from jsonb_array_elements(result->'appointments') x where x->>'id'=b::text and x->>'noShowKind'='unexcused') then raise exception 'Calendar refresh dropped classification'; end if;
 if not exists(select 1 from booking_status_events where booking_id=b and event_type='no_show_classification_changed') then raise exception 'Classification audit missing'; end if;
 if has_function_privilege('anon','public.booking_no_show_history(uuid,uuid)','execute') then raise exception 'Internal history exposed'; end if;
 if has_function_privilege('authenticated','public.manage_pos_portable_booking_before_no_show(uuid,text,uuid,text,jsonb)','execute') then raise exception 'Private helper exposed'; end if;
 update bookings set customer_user_id=pub where id=b;
 result:=get_customer_activity(40);
 if not exists(select 1 from jsonb_array_elements(result->'bookings') x where x->>'bookingId'=b::text and x->>'noShowKind'='unexcused') then raise exception 'Personal history dropped classification'; end if;
 insert into staff(salon_id,display_name,account_user_id) values(s,'Assigned QA staff',pub) returning id into assigned_staff;
 insert into staff_service_assignments(salon_id,staff_id,service_id) values(s,assigned_staff,svc);
 insert into staff_availability_rules(salon_id,staff_id,day_of_week,starts_at_local,ends_at_local) select s,assigned_staff,day,'00:00'::time,'23:59'::time from generate_series(0,6) day;
 insert into bookings(salon_id,customer_id,start_at,end_at,status,confirmation_status) values(s,c,now()+interval '4 days',now()+interval '4 days 30 minutes','pending','requested') returning id into staff_b;
 insert into booking_lines(salon_id,booking_id,service_id,service_name_snapshot,assigned_staff_id,duration_minutes,unit_price,line_total,scheduled_start_at,scheduled_end_at) values(s,staff_b,svc,'Manicure',assigned_staff,30,40,40,now()+interval '4 days',now()+interval '4 days 30 minutes');
 result:=confirm_assigned_booking(staff_b);
 if result->>'code'<>'no_show_review_required' then raise exception 'Staff confirmation bypassed history'; end if;
 result:=confirm_assigned_booking_with_review(staff_b,true);
 if result->>'ok'<>'true' then raise exception 'Assigned staff confirmation failed: %',result; end if;
 if confirm_assigned_booking_with_review(next_b,true)->>'code'<>'forbidden' then raise exception 'Staff confirmed unassigned booking'; end if;
 perform set_config('request.jwt.claim.sub','',true);
 rejected:=false;
 begin perform get_booking_no_show_history(next_b); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Unauthenticated history exposed'; end if;
end;$test$;
rollback;
