-- Run after the migration inside a transaction, then roll back all fixtures.
do $test$
declare a uuid;s uuid;a2 uuid;s2 uuid;u uuid;au uuid;u2 uuid;au2 uuid;admin_u uuid;admin_au uuid;admin_role uuid;j jsonb;r uuid;r2 uuid;stamp timestamptz;denied boolean;role_value uuid;
begin
 au:=gen_random_uuid();u:=gen_random_uuid();au2:=gen_random_uuid();u2:=gen_random_uuid();admin_au:=gen_random_uuid();admin_u:=gen_random_uuid();
 insert into auth.users(id,email) values(au,'claim-'||au||'@example.invalid'),(au2,'claim-'||au2||'@example.invalid'),(admin_au,'claim-'||admin_au||'@example.invalid');
 insert into public.users(id,auth_user_id,email) values(u,au,'claim-'||au||'@example.invalid'),(u2,au2,'claim-'||au2||'@example.invalid'),(admin_u,admin_au,'claim-'||admin_au||'@example.invalid');
 select id into admin_role from public.platform_admin_roles where slug='platform_owner';
 insert into public.platform_admin_memberships(user_id,role_id,status) values(admin_u,admin_role,'active');
 insert into public.accounts(name,status) values('Business claim QA','active') returning id into a;
 insert into public.locations(account_id,name,status,phone,address_line1,address_line2,city,state) values(a,'Claim QA Nails','active','555-234-6789','123 Main Street','Suite 2','Madison','WI') returning id into s;
 insert into public.salon_settings(salon_id,business_name,public_discovery_enabled) values(s,'Claim QA Nails',true) on conflict(salon_id) do update set public_discovery_enabled=true;
 insert into public.booking_settings(salon_id,booking_enabled,online_booking_visible) values(s,false,false) on conflict(salon_id) do update set booking_enabled=false,online_booking_visible=false;
 insert into public.salon_directory_listings(listing_id,salon_id,source_url,source_type,collected_on) values('claim-qa-'||s,s,'https://example.invalid','business_website',current_date);
 if has_function_privilege('authenticated','public.confirm_business_claim(uuid,uuid,text)','execute') or has_function_privilege('authenticated','public.begin_business_claim(uuid,uuid,text)','execute') or has_function_privilege('authenticated','public.complete_business_claim(uuid,uuid,text)','execute') then raise exception 'Browser can self-assign ownership';end if;
 if has_table_privilege('authenticated','public.business_claim_requests','select') or has_table_privilege('anon','public.business_claim_requests','select') then raise exception 'Private claims exposed';end if;
 j:=public.find_business_claim_matches('','+1 (555) 234-6789','123 Main St','Ste 2','Madison','WI');
 if not exists(select 1 from jsonb_array_elements(j) x where x->>'salon_id'=s::text and (x->>'score')::int=100) then raise exception 'Normalized match failed %',j;end if;
 j:=public.find_business_claim_matches('','','123 Main St','Suite 3','Madison','WI');
 if exists(select 1 from jsonb_array_elements(j) x where x->>'salon_id'=s::text and (x->>'address_match')::boolean) then raise exception 'Different suite matched';end if;
 j:=public.begin_business_claim(s,u,'call');r:=(j->>'id')::uuid;stamp:=(j->>'last_sent_at')::timestamptz;
 if j->>'phone'<>'+15552346789' then raise exception 'Phone was not fixed to salon';end if;
 denied:=false;begin perform public.begin_business_claim(s,u2,'sms');exception when others then denied:=true;end;if not denied then raise exception 'Cross-user phone cooldown failed';end if;
 if public.attach_business_claim_challenge(r,u,stamp-interval '1 second','old') then raise exception 'Stale send attached';end if;
 if not public.attach_business_claim_challenge(r,u,stamp,'VE-claim-qa') then raise exception 'Provider not attached';end if;
 denied:=false;begin perform public.reserve_business_claim_check(r,u2);exception when others then denied:=true;end;if not denied then raise exception 'Outsider checked challenge';end if;
 perform set_config('request.jwt.claim.sub',au2::text,true);
 if jsonb_array_length(public.get_business_claim_requests(s))<>0 then raise exception 'Other claimant exposed';end if;
 perform set_config('request.jwt.claim.sub',au::text,true);
 if public.get_business_claim_requests(s)::text like '%provider_sid%' then raise exception 'Provider secret exposed';end if;
 denied:=false;begin perform public.confirm_business_claim(r,u,'wrong-provider');exception when others then denied:=true;end;if not denied then raise exception 'Wrong provider accepted';end if;
 update public.business_claim_requests set expires_at=now()-interval '1 second' where id=r;
 denied:=false;begin perform public.reserve_business_claim_check(r,u);exception when others then denied:=true;end;if not denied then raise exception 'Expired code accepted';end if;
 update public.business_claim_requests set expires_at=now()+interval '10 minutes' where id=r;
 update public.locations set phone='555-234-6799' where id=s;
 denied:=false;begin perform public.confirm_business_claim(r,u,'VE-claim-qa');exception when others then denied:=true;end;if not denied then raise exception 'Changed salon phone accepted';end if;
 update public.locations set phone='555-234-6789' where id=s;
 perform public.reserve_business_claim_check(r,u);
 j:=public.confirm_business_claim(r,u,'VE-claim-qa');
 if j->>'status'<>'approved' then raise exception 'Website phone not auto-approved %',j;end if;
 if not exists(select 1 from public.account_memberships m join public.roles ro on ro.id=m.role_id where m.account_id=a and m.user_id=u and m.status='active' and ro.code='OWNER') then raise exception 'Account owner not granted';end if;
 if not exists(select 1 from public.salon_memberships where salon_id=s and user_id=u and status='active') then raise exception 'Salon owner not granted';end if;
 if exists(select 1 from public.booking_settings where salon_id=s and (booking_enabled or online_booking_visible)) then raise exception 'Claim enabled booking';end if;
 if exists(select 1 from public.get_public_salon_identity(array[s]) where identity_verified) then raise exception 'Claim awarded badge';end if;
 denied:=false;begin perform public.confirm_business_claim(r,u,'VE-claim-qa');exception when others then denied:=true;end;if not denied then raise exception 'Claim replay accepted';end if;
 denied:=false;begin perform public.begin_business_claim(s,u2,'sms');exception when others then denied:=true;end;if not denied then raise exception 'Existing owner overwritten';end if;
 insert into public.accounts(name,status) values('Directory claim QA','active') returning id into a2;
 insert into public.locations(account_id,name,status,phone) values(a2,'Directory QA Nails','active','555-234-6790') returning id into s2;
 insert into public.salon_settings(salon_id,business_name,public_discovery_enabled) values(s2,'Directory QA Nails',true) on conflict(salon_id) do update set public_discovery_enabled=true;
 insert into public.salon_directory_listings(listing_id,salon_id,source_url,source_type,collected_on) values('claim-qa-'||s2,s2,'https://example.invalid','directory',current_date);
 update public.business_claim_sends set sent_at=now()-interval '2 minutes' where applicant_user_id=u;
 j:=public.begin_business_claim(s2,u,'sms');r:=(j->>'id')::uuid;stamp:=(j->>'last_sent_at')::timestamptz;
 perform public.attach_business_claim_challenge(r,u,stamp,'VE-directory-qa');
 for i in 1..5 loop perform public.reserve_business_claim_check(r,u);end loop;
 denied:=false;begin perform public.reserve_business_claim_check(r,u);exception when others then denied:=true;end;if not denied then raise exception 'Attempt cap failed';end if;
 j:=public.confirm_business_claim(r,u,'VE-directory-qa');
 if j->>'status'<>'waiting' then raise exception 'Directory phone auto-approved';end if;
 perform set_config('request.jwt.claim.sub',au2::text,true);
 denied:=false;begin perform public.review_business_claim(r,'approved','fake');exception when others then denied:=true;end;if not denied then raise exception 'Nonadmin approved';end if;
 r2:=public.request_business_claim_support(s2,'I am the owner and the listed phone is outdated.');
 perform public.attach_business_claim_documents(r2,u2,'[{"path":"private-fixture.pdf","name":"Proof.pdf"}]'::jsonb);
 perform public.attach_business_claim_documents(r2,u2,'[{"path":"private-fixture-2.pdf","name":"Proof2.pdf"}]'::jsonb);
 if (select jsonb_array_length(attachments) from public.business_claim_requests where id=r2)<>2 then raise exception 'Documents replaced rather than appended';end if;
 denied:=false;begin perform public.attach_business_claim_documents(r2,u,'[]'::jsonb);exception when others then denied:=true;end;if not denied then raise exception 'Outsider attached documents';end if;
 perform set_config('request.jwt.claim.sub',admin_au::text,true);
 perform public.review_business_claim(r,'approved','Business authority reviewed');
 if (select status from public.business_claim_requests where id=r2)<>'expired' then raise exception 'Competing request not closed';end if;
 denied:=false;begin perform public.review_business_claim(r2,'approved','Second approval');exception when others then denied:=true;end;if not denied then raise exception 'Second claimant approved';end if;
 if (select count(*) from public.business_claim_events where request_id=r and event='approved')<>1 then raise exception 'Approval audit missing';end if;
 -- Ownership recovery requests are accepted but cannot override an existing manager.
 perform set_config('request.jwt.claim.sub',au2::text,true);
 r2:=public.request_business_claim_support(s,'I bought the business and need an ownership recovery review.');
 perform set_config('request.jwt.claim.sub',admin_au::text,true);
 denied:=false;begin perform public.review_business_claim(r2,'approved','Recovery evidence');exception when others then denied:=true;end;if not denied then raise exception 'Claim replaced an owner';end if;
 raise notice 'Business claim integration assertions passed';
end;
$test$;
