begin;
alter table public.bookings disable trigger enforce_booking_time_policy;
do $test$
declare au uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); other_auth uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid(); a uuid; s uuid; c uuid; c2 uuid; svc uuid; b uuid; b2 uuid; ticket uuid; visit uuid; profile uuid; post uuid; review uuid; data jsonb; evidence jsonb; rejected boolean;
begin
 insert into auth.users(id,email) values(au,'history-'||au||'@example.invalid'),(other_auth,'history-'||other_auth||'@example.invalid');
 insert into users(id,auth_user_id,email) values(u,au,'history-'||au||'@example.invalid'),(outsider,other_auth,'history-'||other_auth||'@example.invalid');
 insert into accounts(name,status) values('History QA','active') returning id into a;
 insert into locations(account_id,name,status) values(a,'History salon','active') returning id into s;
 insert into customers(location_id,name,customer_user_id) values(s,'Same name',u) returning id into c;
 insert into customers(location_id,name,customer_user_id) values(s,'Same name',outsider) returning id into c2;
 insert into services(salon_id,name,base_price,duration_minutes) values(s,'Manicure',40,30) returning id into svc;
 insert into bookings(salon_id,customer_id,customer_user_id,start_at,end_at,status,salon_timezone_snapshot)
 values(s,c,u,date_trunc('day',now())-interval '1 day'+interval '16 hours',date_trunc('day',now())-interval '1 day'+interval '17 hours','confirmed','America/Chicago') returning id into b;
 insert into bookings(salon_id,customer_id,customer_user_id,start_at,end_at,status,salon_timezone_snapshot)
 select salon_id,customer_id,customer_user_id,start_at+interval '1 hour',end_at+interval '1 hour','confirmed',salon_timezone_snapshot from bookings where id=b returning id into b2;
 insert into booking_lines(salon_id,booking_id,service_id,service_name_snapshot,duration_minutes,unit_price,line_total) values(s,b,svc,'Manicure',30,40,40);
 insert into pos_tickets(salon_id,customer_id,ticket_number,ticket_sequence,opened_at,closed_at,status) select s,c,'QA-1',1,start_at+interval '10 minutes',end_at,'closed' from bookings where id=b returning id into ticket;
 insert into pos_ticket_items(salon_id,pos_ticket_id,service_id,service_name_snapshot,quantity,unit_price,line_total) values(s,ticket,svc,'Manicure + art',1,55,55);
 insert into customer_visits(salon_id,customer_id,checked_in_at,status,source) select s,c,start_at+interval '5 minutes','waiting','walk_in' from bookings where id=b returning id into visit;
 perform set_config('request.jwt.claim.sub',au::text,true);
 evidence:=get_booking_history_evidence(array[b])->0;
 if evidence->'ticket'<>'null'::jsonb or jsonb_array_length(evidence->'candidates')<>2 then raise exception 'Expected separate same-day ticket/check-in'; end if;
 if find_beauty_visit_proof(u,s,null)->>'method'<>'pos_ticket' then raise exception 'Ticket proof missing'; end if;
 perform set_booking_history_link(b,ticket,'ticket',false);
 evidence:=get_booking_history_evidence(array[b])->0;
 if evidence->'ticket'->>'ticketId'<>ticket::text or evidence->>'manualLink'<>'true' then raise exception 'Merge missing'; end if;
 if (select pos_ticket_id from bookings where id=b) is not null or (select status from bookings where id=b)<>'confirmed' then raise exception 'Display merge changed operations'; end if;
 if (select customer_id from pos_tickets where id=ticket)<>c then raise exception 'Display merge changed ticket'; end if;
 rejected:=false;
 begin perform set_booking_history_link(b2,ticket,'ticket',false); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Ticket linked twice'; end if;
 perform set_booking_history_link(b,b,'visit',true);
 if exists(select 1 from customer_history_links where booking_id=b) then raise exception 'Undo failed'; end if;
 perform set_booking_history_link(b,visit,'visit',false);
 update customer_visits set ticket_id=ticket,status='completed',completed_at=now() where id=visit;
 evidence:=get_booking_history_evidence(array[b])->0;
 if evidence->'ticket'->>'ticketId'<>ticket::text or evidence->>'checkedInAt' is null then raise exception 'Visit merge did not follow later ticket'; end if;
 data:=get_customer_activity(40);
 if data->>'ok'<>'true' or jsonb_array_length(data->'visits')<>1 then raise exception 'Activity visit missing'; end if;
 insert into beauty_profiles(user_id) values(u) returning id into profile;
 insert into beauty_posts(profile_id,author_user_id,post_type) values(profile,u,'before_after') returning id into post;
 insert into beauty_post_attributions(post_id,salon_id) values(post,s);
 insert into beauty_post_verifications(post_id,state,method,booking_id) values(post,'verified','completed_booking',b);
 if (select state from beauty_post_verifications where post_id=post)<>'pending' then raise exception 'Booking proof verified before-after'; end if;
 update beauty_post_verifications set state='verified',method='pos_ticket',pos_ticket_id=ticket where post_id=post;
 if (select state from beauty_post_verifications where post_id=post)<>'verified' then raise exception 'Ticket before-after rejected'; end if;
 insert into salon_profile_reviews(salon_id,author_user_id,rating,body,verification_status) values(s,u,5,'QA review','verified') returning id into review;
 if (select verification_status from salon_profile_reviews where id=review)<>'verified' then raise exception 'Ticket review rejected'; end if;
 perform set_config('request.jwt.claim.sub',other_auth::text,true);
 rejected:=false; begin perform get_booking_history_evidence(array[b]); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Other customer read history'; end if;
 rejected:=false; begin perform set_booking_history_link(b,b,'visit',true); exception when others then rejected:=true; end;
 if not rejected then raise exception 'Other customer changed history'; end if;
 perform set_config('request.jwt.claim.sub',au::text,true);
 update pos_tickets set status='open',closed_at=null where id=ticket;
 if (select state from beauty_post_verifications where post_id=post)='verified' then raise exception 'Reopened ticket still verifies before-after'; end if;
 if (select verification_status from salon_profile_reviews where id=review)='verified' then raise exception 'Reopened ticket still verifies review'; end if;
 if get_booking_history_evidence(array[b])->0->'ticket'<>'null'::jsonb then raise exception 'Reopened ticket counted as paid'; end if;
 update bookings set status='completed' where id=b;
 if find_beauty_visit_proof(u,s,null)->>'state'='verified' then raise exception 'Booking alone verified visit'; end if;
 if has_function_privilege('authenticated','history_ticket_payload(uuid)','execute') then raise exception 'Private ticket helper exposed'; end if;
 if has_table_privilege('authenticated','customer_history_links','insert') then raise exception 'Direct linking bypass allowed'; end if;
end;$test$;
rollback;
