import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{pathToFileURL}from'node:url';
const esbuild=()=>import(pathToFileURL(process.env.ESBUILD_MODULE_PATH).href);
test('first availability searches once and returns the earliest salon day without changing an explicit date',{skip:!process.env.ESBUILD_MODULE_PATH},async()=>{
 const {build}=await esbuild(),source=readFileSync('lib/public-booking.ts','utf8');const fn=source.slice(source.indexOf('function initialAvailableSlots('),source.indexOf('export async function loadPublicBookingRescheduleSlots('));
 const built=await build({stdin:{contents:`const formatDateInTimeZone=(date,tz)=>{const p=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const r=k=>p.find(x=>x.type===k).value;return r('year')+'-'+r('month')+'-'+r('day');};const generatePublicBookingSlots=(c,s,o)=>{globalThis.calls.push({s,o});return s.date===null?[{startAt:c.first}]:c.rows;};`+fn+'export{initialAvailableSlots};',loader:'ts'},write:false,format:'esm',platform:'node'});const{initialAvailableSlots:load}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
 globalThis.calls=[];const context={settings:{timezoneIana:'America/Chicago'},first:'2026-10-04T14:00:00Z',rows:[{startAt:'2026-10-04T14:00:00Z'}]},selection={findEarliest:true,date:'2026-10-02',serviceIds:['full'],staffId:'tracy',staffMode:'specific'};
 assert.deepEqual(load(context,selection,'booking'),context.rows);assert.equal(calls.length,2);assert.equal(calls[0].s.date,null);assert.equal(calls[1].s.date,'2026-10-04');assert.deepEqual(calls[1].s.serviceIds,['full']);assert.equal(calls[1].o.ignoreBookingId,'booking');
 calls.length=0;load(context,{...selection,findEarliest:false});assert.equal(calls.length,1);assert.equal(calls[0].s.date,'2026-10-02');delete globalThis.calls;
});
test('business day follows the salon even when the account and device are in Vietnam',{skip:!process.env.ESBUILD_MODULE_PATH},async()=>{
 const {build}=await esbuild();const built=await build({entryPoints:['lib/salon-business-clock.ts'],bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'clock',setup(b){b.onResolve({filter:/^(server-only|react|@\/lib\/supabase\/server)$/},a=>({path:a.path,namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:'export const cache=f=>f;export const createAuthenticatedSupabaseServerClient=async()=>({rpc:async()=>globalThis.clockResult});',loader:'js'}));}}]});const api=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
 const RealDate=globalThis.Date;try{globalThis.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-10-03T00:30:00Z']));}};globalThis.clockResult={data:'America/Chicago',error:null};const context={user:{timezone:'Asia/Ho_Chi_Minh'},currentSalon:{id:'salon'}};assert.equal(await api.getContextBusinessDate(context),'2026-10-02');assert.equal(await api.getContextBusinessTimezone(context),'America/Chicago');clockResult={data:null,error:null};await assert.rejects(()=>api.getContextBusinessDate(context),/Salon clock/);}finally{globalThis.Date=RealDate;delete globalThis.clockResult;}
});
