import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright-core';

test('Portable: inline edits, three services, available duration, status, and POS handoff', {timeout:60000,skip:!process.env.ESBUILD_MODULE_PATH||!process.env.TEST_BROWSER_PATH},async()=>{
 const {build}=await import(pathToFileURL(process.env.ESBUILD_MODULE_PATH).href);
 const built=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
 import React from 'react';import{createRoot}from'react-dom/client';import{PortableBookWorkspace}from'./app/pos/portable/book/portable-book-workspace';
 const services=[{id:'a',name:'Manicure',duration_minutes:30},{id:'b',name:'Pedicure',duration_minutes:40},{id:'c',name:'Polish',duration_minutes:20}];
 let item={id:'booking',customerId:'customer',customerName:'Maya',customerPhone:'555',serviceIds:['a'],serviceNames:['Manicure'],staffId:'alice',staffName:'Alice',startAt:'2026-09-25T14:00:00.000Z',endAt:'2026-09-25T14:30:00.000Z',status:'pending',updatedAt:'version1'};
 window.manageCalls=[];window.slotCalls=[];window.busy=true;
 window.addEventListener('kingpos:booking-ticket',event=>{if(window.busy){event.detail.respond('Save the current POS ticket first.');return;}window.handoff=event.detail.appointment;event.detail.respond();});
 const manage=async request=>{window.manageCalls.push(request);if(request.action==='edit'){const p=request.payload;item={...item,serviceIds:p.serviceIds,serviceNames:p.serviceIds.map(id=>services.find(s=>s.id===id).name),staffId:p.staffIds[0],staffName:p.staffIds[0]==='bob'?'Bob':'Alice',startAt:p.startAt,endAt:new Date(Date.parse(p.startAt)+p.serviceIds.reduce((n,id)=>n+services.find(s=>s.id===id).duration_minutes,0)*60000).toISOString()};}if(request.action==='confirm')item={...item,status:'confirmed'};if(request.action==='cancel')item={...item,status:'cancelled'};return{ok:true,data:{...item,lines:item.serviceIds.map(id=>({id,serviceId:id,serviceName:services.find(s=>s.id===id).name,staffId:item.staffId,price:30}))}};};
 const slots=async input=>{window.slotCalls.push(input);return[{startAt:'2026-09-25T14:00:00.000Z',label:'09:00',endAt:new Date(Date.parse('2026-09-25T14:00:00Z')+input.serviceIds.reduce((n,id)=>n+services.find(s=>s.id===id).duration_minutes,0)*60000).toISOString()}]};
 createRoot(document.getElementById('root')).render(<PortableBookWorkspace data={{appointments:[item],date:'2026-09-25',timezone:'America/Chicago',salonName:'Fixture',canCreate:true,canCancel:true,canCreateTicket:true,services,staffServiceAssignments: services.flatMap(service => ["alice","bob"].map(staffId=>({serviceId:service.id,staffId}))),staff:[{id:'alice',display_name:'Alice'},{id:'bob',display_name:'Bob'}],setupMessage:null}} action={async()=>({ok:false,error:'unused'})} manageAction={manage} slotsAction={slots}/>);
 `},bundle:true,write:false,outdir:'fixture',jsx:'automatic',plugins:[{name:'workspace',setup(b){b.onResolve({filter:/portable-workspace-state$/},()=>({path:'stub',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:'export const usePortableWorkspaceState=()=>null;'}));}}]});
 const js=built.outputFiles.find(f=>f.path.endsWith('.js')).text,css=built.outputFiles.find(f=>f.path.endsWith('.css')).text;
 const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/app.js'?'text/javascript':req.url==='/app.css'?'text/css':'text/html');res.end(req.url==='/app.js'?js:req.url==='/app.css'?css:'<link rel="stylesheet" href="/app.css"><div id="root"></div><script src="/app.js"></script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH,headless:true});
 try{const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-24T18:00:00Z'));await page.goto('http://127.0.0.1:'+server.address().port+'/pos/portable/book');
 await page.getByRole('button',{name:'Change professional for Maya'}).click();await page.getByRole('button',{name:/Bob Availability checked/}).click();await page.getByRole('button',{name:'Add service',exact:false}).click();await page.getByRole('button',{name:'Pedicure, 40 min',exact:true}).click();await page.getByRole('button',{name:'Polish, 20 min',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:/Sep 25/}).click();
 await page.getByRole('button',{name:/09:00.*90 min/}).click();await page.getByRole('button',{name:'Save changes'}).click();await page.getByRole('region',{name:'Edit appointment',exact:true}).waitFor({state:'detached'});assert.match(await page.getByRole('table').textContent(),/90 min/);assert.match(await page.getByRole('button',{name:'Change professional for Maya'}).textContent(),/Bob/);
 assert.deepEqual(await page.evaluate(()=>window.manageCalls.find(c=>c.action==='edit').payload.serviceIds),['a','b','c']);assert.equal(await page.evaluate(()=>window.slotCalls.at(-1).bookingId),'booking');
 await page.getByRole('button',{name:'Change status for Maya'}).click();await page.getByRole('button',{name:'Confirm appointment',exact:true}).click();await page.getByRole('button',{name:'Create ticket for Maya'}).waitFor();
 await page.getByRole('button',{name:'Create ticket for Maya'}).click();await page.getByRole('alert').waitFor();assert.match(await page.getByRole('alert').textContent(),/current POS ticket/);assert.ok(page.url().endsWith('/pos/portable/book'));
 await page.evaluate(()=>window.busy=false);await page.getByRole('button',{name:'Create ticket for Maya'}).click();await page.waitForFunction(()=>location.pathname==='/pos/portable');assert.equal(await page.evaluate(()=>window.handoff.lines.length),3);
 await page.getByRole('button',{name:'Change status for Maya'}).click();await page.getByLabel('Cancellation reason (optional)').fill('Customer request');await page.getByRole('button',{name:'Cancel appointment',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});assert.match(await page.getByRole('table').textContent(),/Cancelled/);assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
