import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {chromium} from 'playwright-core';
test('Targeted staff updates, lost receipt reply acknowledgement and remote checkout preserve local work',{skip:!process.env.ESBUILD_MODULE_PATH||!process.env.TEST_BROWSER_PATH,timeout:45000},async()=>{
 const {build}=await import(pathToFileURL(process.env.ESBUILD_MODULE_PATH).href);const root=resolve('.').replaceAll('\\','/');const id='11111111-1111-4111-8111-111111111111';const salon='22222222-2222-4222-8222-222222222222';
 const bundle=await build({stdin:{resolveDir:root,loader:'tsx',contents:`import React from'react';import{createRoot}from'react-dom/client';import{PortableWorkspaceStateProvider,usePortableWorkspaceState,mergePortableStaff}from'${root}/app/pos/portable/portable-workspace-state';
 const at=new Date().toISOString();window.ops=[{id:'pending-receipt',kind:'receipt',state:'pending',occurredAt:at,payload:{staffAttendance:{'${id}':{status:'working',queueTurnCount:2}},staffTurnDeltas:{'${id}':1}}}];
 function Probe(){const w=usePortableWorkspaceState();const rows=mergePortableStaff([],w);return <><input aria-label="Unfinished amount" defaultValue="45"/><output>{rows.map(s=>s.display_name+':'+s.turns.queueTurns).join(',')}</output></>;}createRoot(document.getElementById('root')).render(<PortableWorkspaceStateProvider scope="${salon}:key" offlineEnabled><Probe/></PortableWorkspaceStateProvider>);`},jsx:'automatic',bundle:true,write:false,platform:'browser',plugins:[{name:'fixtures',setup(b){
 b.onResolve({filter:/supabase\/browser$/},()=>({path:'supabase',namespace:'fixture'}));b.onResolve({filter:/lib\/portable-operations$/},()=>({path:'ops',namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='ops'?`export const PORTABLE_OPERATIONS_CHANGED='ops';export const listPortableOperations=async()=>window.ops;`:`export function createSupabaseBrowserClient(){const channel={on(type,filter,cb){window.emit=payload=>cb({payload});return channel;},subscribe(){return channel;}};return{channel:()=>channel,removeChannel(){}};}`}));}}]});
 let committed=false,checkedOut=false;const requests=[];
 const server=createServer((req,res)=>{if(req.url==='/bundle.js'){res.setHeader('Content-Type','text/javascript');res.end(bundle.outputFiles[0].text);return;}
 if(req.url.startsWith('/api/')){res.setHeader('Content-Type','application/json');if(req.url.includes('resource=settings')){res.end('{}');return;}
 requests.push(req.url);const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago'}).format(new Date());res.end(JSON.stringify({today,staff:[{id,display_name:'Alice',is_active:true,today_status:checkedOut?'checked_out':'working',check_in_at:new Date().toISOString(),turns:{queueTurns:committed?2:1}}],acknowledgedOperationIds:committed?['pending-receipt']:[]}));return;}
 res.setHeader('Content-Type','text/html');res.end('<div id="root"></div><script src="/bundle.js"></script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH,headless:true});
 try{const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>document.querySelector('output')?.textContent==='Alice:2');
 committed=true;await page.evaluate(({salon,id})=>window.emit({salonId:salon,resource:'staff',ids:[id]}),{salon,id});await page.waitForResponse(response=>response.url().includes('ids='));await page.waitForTimeout(200);assert.equal(await page.locator('output').innerText(),'Alice:2','committed receipt with lost reply must not add its turn twice');assert.ok(requests.at(-1).includes('ids='+id));
 checkedOut=true;await page.evaluate(({salon,id})=>window.emit({salonId:salon,resource:'staff',ids:[id]}),{salon,id});await page.waitForFunction(()=>document.querySelector('output')?.textContent==='');assert.equal(await page.getByLabel('Unfinished amount').inputValue(),'45');assert.equal(await page.evaluate(()=>window.ops[0].state),'pending');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
