import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';

test('booking intents skip only known valid choices and preserve staff-only intent', {skip:!process.env.ESBUILD_MODULE_PATH},async()=>{
  const source=readFileSync('lib/public-booking.ts','utf8');
  const body=source.slice(source.indexOf('function normalizeInitialSelection('),source.indexOf('export async function getPublicBookingPageData('));
  const prelude=`const singleParam=v=>Array.isArray(v)?v[0]:v;const cleanSource=v=>v??'public_profile';const cleanUuid=v=>typeof v==='string'&&v?v:null;const inspirationParam=p=>singleParam(p.inspiration)??null;const contentOptionForInspiration=(c,id)=>c.contentOptions.find(o=>o.contentId===id);const eligibleStaffIds=(c,id)=>c.eligible[id]??[];const selectionLines=(c,s)=>[...s.serviceIds.map(id=>({id})),...s.addOnSelections.map(a=>({id:a.serviceId}))];const staffCanPerformLines=(c,lines,id)=>lines.every(l=>eligibleStaffIds(c,l.id).includes(id));const addOnSelectionsFromOption=(c,ids,o)=>o.addOns??[];const cleanDate=v=>v??null;const formatDateInTimeZone=()=> '2099-10-02';const buildContentInspiration=v=>({...v,sourceType:v.option.sourceType});const lookServiceEligible=()=>false;const firstBookableServiceId=c=>c.serviceMap.keys().next().value;const buildInspiration=()=>null;`;
  const {build}=await import(pathToFileURL(process.env.ESBUILD_MODULE_PATH).href);
  const built=await build({stdin:{contents:prelude+body+'export {normalizeInitialSelection};',loader:'ts'},bundle:true,write:false,format:'esm',platform:'node'});
  const {normalizeInitialSelection:select}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
  const context={settings:{timezoneIana:'America/Chicago',anyProfessionalEnabled:true},contentOptions:[],looks:[],staff:[{id:'tracy'},{id:'lucy'}],eligible:{full:['tracy'],gel:['lucy'],art:['tracy']},serviceMap:new Map([['full',{id:'full',isAddOnOnly:false}],['gel',{id:'gel',isAddOnOnly:false}],['art',{id:'art',isAddOnOnly:true}]])};
  let selection=select(context,{serviceId:'full',staffId:'tracy'});assert.equal(selection.initialStep,2);assert.equal(selection.staffId,'tracy');assert.deepEqual(selection.serviceIds,['full']);
  selection=select(context,{serviceId:'full'});assert.equal(selection.initialStep,1);
  selection=select(context,{staffId:'lucy'});assert.equal(selection.initialStep,0);assert.equal(selection.staffId,'lucy');assert.deepEqual(selection.serviceIds,[],'staff-only must not silently select a default service');
  selection=select(context,{serviceId:'removed',staffId:'tracy'});assert.equal(selection.initialStep,0);assert.deepEqual(selection.serviceIds,[]);
  selection=select(context,{serviceId:'full',staffId:'lucy'});assert.equal(selection.initialStep,1);assert.equal(selection.staffId,null,'ineligible staff requires an explicit choice');
  context.contentOptions=[{contentId:'post',primaryServiceId:'full',additionalServices:[],addOns:[{parentServiceId:'full',serviceId:'art'}],creditedStaffId:'tracy',creditedStaffName:'Tracy',readinessState:'quick_ready',sourceType:'beauty_post'}];
  selection=select(context,{inspiration:'post',source:'explore'});assert.equal(selection.initialStep,2);assert.equal(selection.staffId,'tracy');assert.deepEqual(selection.addOnSelections,[{parentServiceId:'full',serviceId:'art'}]);assert.equal(selection.inspiration.sourceType,'beauty_post');
  context.contentOptions[0].sourceType='salon_profile_look';context.contentOptions[0].readinessState='service_ready';selection=select(context,{inspiration:'post'});assert.equal(selection.initialStep,2,'legacy service_ready metadata with valid staff still goes straight to time');assert.equal(selection.staffId,'tracy');
  context.contentOptions[0].additionalServices=[{serviceId:'removed'}];selection=select(context,{inspiration:'post'});assert.equal(selection.initialStep,0,'incomplete recipe must be reviewed before choosing time');context.contentOptions[0].additionalServices=[];
  const pageFunction=source.slice(source.indexOf('export async function getPublicBookingPageData('),source.indexOf('export async function loadPublicBookingSlots('));
  const pageBuilt=await build({stdin:{contents:prelude+body+`const toIso=v=>v?new Date(v).toISOString():null;const loadRawContext=async()=>globalThis.quickSelectionContext;const getCurrentKingUser=async()=>null;const createAuthenticatedSupabaseServerClient=async()=>null;const readinessForContext=()=>[];const staffByService=c=>c.eligible;const unavailablePage=(state,title,message,base)=>({...base,state,title,message});const generatePublicBookingSlots=(c,input,options)=>{globalThis.quickSelectionRequests.push(input);return globalThis.quickSelectionSlots;};`+pageFunction,loader:'ts'},bundle:true,write:false,format:'esm',platform:'node'});
  const {getPublicBookingPageData:getPage}=await import('data:text/javascript;base64,'+Buffer.from(pageBuilt.outputFiles[0].text).toString('base64'));
  context.state='ready';context.profile={name:'King Nails'};context.services=[...context.serviceMap.values()];
  globalThis.quickSelectionContext=context;globalThis.quickSelectionRequests=[];globalThis.quickSelectionSlots=[{startAt:'2099-10-02T16:00:00.000Z'}];
  const exact=await getPage('salon',{inspiration:'post',startAt:'2099-10-02T16:00:00Z'});
  assert.equal(exact.initialSelection.initialStep,3);assert.equal(exact.initialSelection.startAt,'2099-10-02T16:00:00.000Z');assert.deepEqual(globalThis.quickSelectionRequests[0].addOnSelections,[{parentServiceId:'full',serviceId:'art'}]);
  globalThis.quickSelectionSlots=[];
  const lost=await getPage('salon',{inspiration:'post',startAt:'2099-10-02T16:00:00Z'});
  assert.equal(lost.state,'ready','scoped intent stays editable when its slot is lost');assert.equal(lost.initialSelection.initialStep,2);assert.equal(lost.initialSelection.requestedTimeUnavailable,true);assert.equal(lost.initialSelection.startAt,undefined);
  globalThis.quickSelectionRequests=[];
  const deferred=await getPage('salon',{}, {deferAvailability:true});
  assert.equal(deferred.state,'ready');assert.deepEqual(deferred.slots,[]);assert.deepEqual(globalThis.quickSelectionRequests,[],'opening a popup must not wait for slot generation or future-slot probing');
  globalThis.quickSelectionSlots=[{startAt:'2099-10-02T16:00:00.000Z'}];globalThis.quickSelectionRequests=[];
  const quick=await getPage('salon',{inspiration:'post'},{deferAvailability:true,resolveKnownAvailability:true});
  assert.equal(quick.initialSelection.initialStep,2);assert.equal(quick.availabilityResolved,true);
  assert.equal(quick.slots.length,1,'known post includes availability in the initial response');
  assert.equal(globalThis.quickSelectionRequests.length,1,'known post does not need a second availability loader');
  globalThis.quickSelectionRequests=[];
  const staffOnly=await getPage('salon',{staffId:'tracy'},{deferAvailability:true,resolveKnownAvailability:true});
  assert.equal(staffOnly.initialSelection.initialStep,0);assert.deepEqual(staffOnly.slots,[]);assert.deepEqual(globalThis.quickSelectionRequests,[],'do not calculate times until required choices exist');
  for(const key of ['quickSelectionContext','quickSelectionRequests','quickSelectionSlots'])delete globalThis[key];
});
