-- Run with the migration in the same transaction before deployment; all fixtures roll back.
do $test$
declare a uuid;s uuid;hidden uuid;u uuid;au uuid;admin_u uuid;admin_au uuid;outsider uuid;outsider_au uuid;owner_role uuid;admin_role uuid;r uuid;r2 uuid;r3 uuid;j jsonb;c uuid;b uuid;service1 uuid;service2 uuid;rec record;
begin
 insert into accounts(name,status) values('Identity rollback QA','active') returning id into a;
 insert into locations(account_id,name,status) values(a,'Identity QA','active') returning id into s;
 insert into locations(account_id,name,status) values(a,'Hidden QA','active') returning id into hidden;
 insert into salon_settings(salon_id,business_name,public_discovery_enabled) values(s,'Identity QA',true),(hidden,'Hidden QA',false) on conflict(salon_id) do update set public_discovery_enabled=excluded.public_discovery_enabled;
 au:=gen_random_uuid();u:=gen_random_uuid();admin_au:=gen_random_uuid();admin_u:=gen_random_uuid();outsider_au:=gen_random_uuid();outsider:=gen_random_uuid();
 insert into auth.users(id,email) values(au,'qa-'||au||'@example.invalid'),(admin_au,'qa-'||admin_au||'@example.invalid'),(outsider_au,'qa-'||outsider_au||'@example.invalid');
 insert into users(id,auth_user_id,email) values(u,au,'qa-'||au||'@example.invalid'),(admin_u,admin_au,'qa-'||admin_au||'@example.invalid'),(outsider,outsider_au,'qa-'||outsider_au||'@example.invalid');
 select id into owner_role from roles where account_id=a and upper(code)='OWNER';
 if owner_role is null then insert into roles(account_id,name,code) values(a,'Owner','OWNER') returning id into owner_role; end if;
 insert into account_memberships(account_id,user_id,role_id,status) values(a,u,owner_role,'active');
 select id into admin_role from platform_admin_roles where slug='platform_owner';
 insert into platform_admin_memberships(user_id,role_id,status) values(admin_u,admin_role,'active');
 if has_function_privilege('authenticated','public.begin_salon_verification(uuid,uuid,text,text,text,text,jsonb)','execute') then raise exception 'Browser may create a known OTP hash'; end if;
 if has_table_privilege('authenticated','public.salon_verification_requests','select') then raise exception 'Private application exposed'; end if;
 begin perform begin_salon_verification(s,outsider,'Test salon','123 Main St','+15551234567','fake');raise exception 'Outsider accepted'; exception when others then if sqlerrm='Outsider accepted' then raise;end if;end;
 r:=begin_salon_verification(s,u,'Test salon','123 Main St','+15551234567',encode(extensions.digest('+15551234567:123456','sha256'),'hex'));
 perform set_config('request.jwt.claim.sub',outsider_au::text,true);
 begin perform confirm_salon_verification(r,'123456');raise exception 'Outsider confirmed'; exception when others then if sqlerrm='Outsider confirmed' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',au::text,true);
 j:=get_salon_verification_requests(s);
 if j::text like '%otp_hash%' then raise exception 'OTP secret leaked';end if;
 j:=confirm_salon_verification(r,null);if(j->>'ok')::boolean then raise exception 'Null code accepted';end if;
 j:=confirm_salon_verification(r,'999999');if(j->>'ok')::boolean then raise exception 'Wrong code accepted';end if;
 j:=confirm_salon_verification(r,'123456');if not(j->>'ok')::boolean then raise exception 'Correct code failed %',j;end if;
 select * into rec from get_public_salon_identity(array[s]);if rec.identity_verified then raise exception 'Waiting badge turned blue';end if;
 perform set_config('request.jwt.claim.sub',outsider_au::text,true);
 begin perform review_salon_verification(r,'approved');raise exception 'Outsider reviewed'; exception when others then if sqlerrm='Outsider reviewed' then raise;end if;end;
 perform set_config('request.jwt.claim.sub',admin_au::text,true);
 perform review_salon_verification(r,'rejected','Address unclear');
 update salon_verification_requests set last_sent_at=now()-interval '2 minutes' where id=r;
 r2:=begin_salon_verification(s,u,'Test salon','123 Main St','+15551234567',encode(extensions.digest('+15551234567:123456','sha256'),'hex'),'[]');
 if (select attempt from salon_verification_requests where id=r2)<>2 then raise exception 'Retry numbering failed';end if;
 perform set_config('request.jwt.claim.sub',au::text,true);perform confirm_salon_verification(r2,'123456');
 perform set_config('request.jwt.claim.sub',admin_au::text,true);perform review_salon_verification(r2,'rejected','Still unclear');perform review_salon_verification(r2,'blocked','Repeated invalid identity');
 update salon_verification_requests set last_sent_at=now()-interval '2 minutes' where id=r2;
 begin perform begin_salon_verification(s,u,'Test salon','123 Main St','+15551234567','fake');raise exception 'Blocked salon reapplied';exception when others then if sqlerrm='Blocked salon reapplied' then raise;end if;end;
 if (select status from users where id=u)='suspended' then raise exception 'Owner account suspended';end if;
 perform review_salon_verification(r2,'unblock','Ready for another application');
 r3:=begin_salon_verification(s,u,'Test salon','123 Main St','+15551234567',encode(extensions.digest('+15551234567:123456','sha256'),'hex'));
 perform set_config('request.jwt.claim.sub',au::text,true);perform confirm_salon_verification(r3,'123456');
 perform set_config('request.jwt.claim.sub',admin_au::text,true);perform review_salon_verification(r3,'approved');
 select * into rec from get_public_salon_identity(array[s]);if not rec.identity_verified then raise exception 'Approval did not grant badge';end if;
 if exists(select 1 from get_public_salon_identity(array[hidden])) then raise exception 'Private salon leaked';end if;
 if (select count(*) from salon_verification_decisions where request_id=r2)<>3 then raise exception 'Decision history lost';end if;
 insert into customers(location_id,name) values(s,'QA customer') returning id into c;
 insert into services(salon_id,name,category,base_price,is_active) values(s,'Basic pedicure','Pedicure',40,true) returning id into service1;
 insert into services(salon_id,name,category,base_price,is_active) values(s,'Deluxe pedicure','Pedicure',100,true) returning id into service2;
 insert into bookings(salon_id,customer_id,start_at,end_at,status) values(s,c,now()+interval '2 days',now()+interval '49 hours','completed') returning id into b;
 insert into booking_lines(salon_id,booking_id,service_id,service_name_snapshot,line_type,line_status) values(s,b,service1,'Basic pedicure','service','completed'),(s,b,service2,'Deluxe pedicure','service','completed');
 insert into bookings(salon_id,customer_id,start_at,end_at,status) values(s,c,now()+interval '1 day',now()+interval '25 hours','confirmed') returning id into b;
 insert into booking_lines(salon_id,booking_id,service_id,service_name_snapshot,line_type) values(s,b,service1,'Basic pedicure','service');
 select * into rec from get_public_salon_identity(array[s]);
 if rec.service_name<>'Pedicure' or rec.minimum_price<>40 or rec.maximum_price<>100 or rec.completed_booking_count<>1 then raise exception 'Completed booking group price failed %',row_to_json(rec);end if;
 select * into rec from get_public_salon_service_prices(array[service2]);
 if rec.base_price<>100 or rec.service_name<>'Deluxe pedicure' then raise exception 'Specific service price was replaced by the salon minimum';end if;
end;
$test$;
