import test from 'node:test';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {chromium} from 'playwright-core';

test('owners and closure records show concrete identities and perform inline target actions', {skip:!process.env.ESBUILD_MODULE_PATH,timeout:90000},async()=>{
 const {build}=await import(pathToFileURL(process.env.ESBUILD_MODULE_PATH).href);
 const result=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`import React from 'react';import{createRoot}from'react-dom/client';import{OwnershipSettingsPanel,LifecycleSettingsPanel}from'./app/settings/ownership-lifecycle-panels';window.calls=[];window.saved=0;const common={salonId:'second',salonName:'King Nails'};createRoot(document.getElementById('root')).render(<><OwnershipSettingsPanel data={{...common,kind:'ownership',roster:{owners:[{id:'ny',email:'ny@example.com',isCurrentUser:false}],canLeave:true},history:[{id:'old',email:'former@example.com',date:'2026-09-01T12:00:00Z'}],historyError:null,invites:[]}} onSaved={async()=>window.saved++}/><LifecycleSettingsPanel data={{...common,kind:'close-salon',lifecycle:{lifecycleStatus:'active'},review:{canClose:false,blockingRecords:[{id:'open_pos_tickets',count:1,label:'Open POS tickets'}]},closureDetails:{appointments:[{id:'booking',customer:{name:'Jane',phone:'123'},staff:{display_name:'Alex'},start_at:'2026-10-06T12:00:00Z',updated_at:'version-booking',status:'confirmed'}],tickets:[{id:'ticket',ticket_number:123,customer:{name:'Sam'},opened_at:'2026-10-06T12:00:00Z',updated_at:'version-ticket'}]}}} onSaved={async()=>window.saved++}/></>);`},bundle:true,write:false,outdir:'fixture',jsx:'automatic',plugins:[{name:'stub',setup(b){
 b.onResolve({filter:/\.\/direct-settings-actions$/},()=>({path:'actions',namespace:'stub'}));b.onResolve({filter:/\.\/settings-extra-actions$/},()=>({path:'extra',namespace:'stub'}));
 b.onLoad({filter:/.*/,namespace:'stub'},a=>({loader:'js',contents:a.path==='actions'?`export async function runDirectOwnership(salonId,form){window.calls.push({salonId,mode:form.get('mode'),email:form.get('email')});return {ok:true}}export async function runDirectLifecycle(){return {ok:true}}`:`export async function downloadSettingsSalonBackup(){return {error:'Fixture'}}export async function resolveSettingsClosureRecord(salonId,input){window.calls.push({salonId,input});return {ok:true}}`}));
 }}]});
 const browser=await chromium.launch({executablePath:process.env.TEST_BROWSER_PATH,headless:true});
 try{const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('http://localhost/',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div><script src="/app.js"></script>'}));await page.route('**/app.js',r=>r.fulfill({contentType:'text/javascript',body:result.outputFiles.find(f=>f.path.endsWith('.js')).text}));await page.goto('http://localhost/');
  await page.getByText('ny@example.com owns King Nails').waitFor();await page.getByText('Former owners',{exact:true}).click();await page.getByText(/former@example.com left ownership of King Nails/).waitFor();
  await page.getByText('Transfer ownership',{exact:true}).click();const transfer=page.locator('details').filter({has:page.locator('summary').filter({hasText:/^Transfer ownership$/})});await transfer.getByLabel('Recipient email').fill('next@example.com');await transfer.getByRole('button',{name:'Send invitation',exact:true}).click();await page.waitForFunction(()=>window.saved===1);
  await page.getByText('Permanently close salon',{exact:true}).click();await page.locator('summary').filter({hasText:/Ticket 123/}).click();const ticket=page.locator('form').filter({has:page.getByRole('button',{name:'Cancel open ticket',exact:true})});await ticket.getByLabel('Cancellation reason').fill('Salon closure');await ticket.getByLabel('Confirm ticket cancellation').check();await ticket.getByRole('button',{name:'Cancel open ticket',exact:true}).click();await page.waitForFunction(()=>window.saved===2);
  const calls=await page.evaluate(()=>window.calls);assert.deepEqual(calls[0],{salonId:'second',mode:'transfer_ownership',email:'next@example.com'});assert.deepEqual(calls[1],{salonId:'second',input:{kind:'ticket',id:'ticket',updatedAt:'version-ticket',reason:'Salon closure',confirmed:true}});assert.equal(page.url(),'http://localhost/');assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
