export type Staff = {
  id: string;
  organization_id: string;
  salon_id: string;
  account_user_id: string | null;
  user_id: string | null;
  display_name: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  email: string | null;
  job_title: string | null;
  public_profile_photo_path: string | null;
  public_bio: string | null;
  public_profile_visible: boolean;
  owner_public_enabled: boolean;
  staff_public_consent_status: "granted" | "not_requested" | "opted_out";
  online_booking_enabled: boolean;
  profile_display_order: number;
  salon_profile_content_posting_enabled: boolean;
  specialties: string[];
  is_active: boolean;
  created_at: string;
  updated_at: string;
};

export type CreateStaffInput = {
  display_name: string;
  first_name?: string | null;
  last_name?: string | null;
  phone?: string | null;
  email?: string | null;
  job_title?: string | null;
  public_bio?: string | null;
  public_profile_photo_path?: string | null;
  public_profile_visible?: boolean;
  owner_public_enabled?: boolean;
  staff_public_consent_status?: "granted" | "not_requested" | "opted_out";
  online_booking_enabled?: boolean;
  profile_display_order?: number;
  salon_profile_content_posting_enabled?: boolean;
  specialties?: string[];
  is_active?: boolean;
};
