import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SalonSwitcher } from "@/app/salon-switcher";
import { getCurrentBusinessContext } from "@/lib/current-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const context = await getCurrentBusinessContext();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full bg-zinc-50 antialiased`}
    >
      <body className="min-h-full flex flex-col bg-zinc-50 text-zinc-950">
        <SalonSwitcher context={context} />
        {children}
      </body>
    </html>
  );
}
