"use client";
import {useEffect,useRef,useState} from "react";
export function PostActions({onOpen,onShare,onFeature,onArchive,onDelete,isFeatured=false,disabled=false}: {onOpen?:()=>void;onShare?:()=>void;onFeature?:()=>void;onArchive?:()=>void;onDelete?:()=>void;isFeatured?:boolean;disabled?:boolean}) {
 const ref=useRef<HTMLDetailsElement>(null);
 const [open,setOpen]=useState(false);
 const [busy,setBusy]=useState(false);
 const [position,setPosition]=useState({left:8,top:8});
 useEffect(()=>{if(!open)return;function close(event:Event){if(event.target instanceof Node && !ref.current?.contains(event.target))ref.current?.removeAttribute("open");}function escape(event:KeyboardEvent){if(event.key === "Escape"){event.stopPropagation();ref.current?.removeAttribute("open");ref.current?.querySelector<HTMLElement>("summary")?.focus();}}document.addEventListener("pointerdown",close,true);document.addEventListener("focusin",close,true);document.addEventListener("keydown",escape,true);const navigation=()=>ref.current?.removeAttribute("open");document.addEventListener("reylumi:overlay-navigation",navigation);return()=>{document.removeEventListener("pointerdown",close,true);document.removeEventListener("focusin",close,true);document.removeEventListener("keydown",escape,true);document.removeEventListener("reylumi:overlay-navigation",navigation);};},[open]);
 const actions=[{label:"View post",action:onOpen},{label:isFeatured?"Remove featured selection":"Use as featured photo",action:onFeature},{label:"Share post",action:onShare},{label:"Archive post",action:onArchive},{label:"Delete post",action:onDelete}].filter(item=>item.action);
 return <details ref={ref} data-dismissible-popover onToggle={event=>{const expanded=event.currentTarget.open;if(expanded){const box=event.currentTarget.querySelector("summary")!.getBoundingClientRect();setPosition({left:Math.max(8,Math.min(box.right-208,window.innerWidth-216)),top:Math.max(8,Math.min(box.bottom+4,window.innerHeight-actions.length*44-28))});}setOpen(expanded);}} className="relative" style={{position:"relative",zIndex:open?45:2}}><summary aria-label="Post actions" aria-haspopup="menu" aria-expanded={open} className="grid size-9 cursor-pointer list-none place-items-center rounded-full bg-white/95 text-zinc-700 shadow-sm hover:bg-white [&::-webkit-details-marker]:hidden" style={{display:"grid",placeItems:"center",width:36,height:36,borderRadius:18,background:"rgba(255,255,255,.95)",cursor:"pointer",listStyle:"none"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><circle cx="5" cy="12" r="1.7"/><circle cx="12" cy="12" r="1.7"/><circle cx="19" cy="12" r="1.7"/></svg></summary>{open?<div role="menu" className="absolute right-0 top-10 grid w-52 rounded-xl border border-zinc-200 bg-white p-1.5 shadow-lg" style={{position:"fixed",left:position.left,top:position.top,zIndex:100,width:208,background:"white",padding:6,borderRadius:12,boxShadow:"0 8px 24px #0002",border:"1px solid #e7e5e4"}}>{actions.map(item=><button key={item.label} role="menuitem" type="button" disabled={disabled || busy} className="min-h-11 rounded-lg px-3 text-left text-sm text-zinc-700 hover:bg-zinc-50 disabled:opacity-50" style={{display:"block",width:"100%",minHeight:44,textAlign:"left",padding:"8px 12px",fontSize:13}} onClick={async()=>{ref.current?.removeAttribute("open");setBusy(true);try{await item.action?.();}finally{setBusy(false);}}}>{item.label}</button>)}</div>:null}</details>;
}
