name: Reylumi
options:
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    CODE_SIGN_STYLE: Automatic
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
targets:
  Reylumi:
    type: application
    platform: iOS
    sources: [Reylumi]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reylumi.ios
        INFOPLIST_FILE: Reylumi/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
  ReylumiTests:
    type: bundle.unit-test
    platform: iOS
    sources: [ReylumiTests]
    dependencies:
      - target: Reylumi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.reylumi.ios.tests
        GENERATE_INFOPLIST_FILE: YES
schemes:
  Reylumi:
    build:
      targets:
        Reylumi: all
    test:
      targets: [ReylumiTests]
