import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader, AdminSection, StatusBadge, formatAdminDateTime } from "../../_components/admin-ui";
import { AdminActionForm } from "../../_components/action-form";
import { requirePlatformAdmin } from "@/lib/platform-admin/auth";
import { PLATFORM_ADMIN_PERMISSIONS as P } from "@/lib/platform-admin/permissions";
import { getSupportThread } from "@/lib/platform-admin/inbox";
import { getSupportEmailConfig, publicSupportEmailConfig, supportEmailReady } from "@/lib/support-email";
import { SUPPORT_EMAIL, SUPPORT_STATUSES, SUPPORT_STATUS_LABELS, supportMailto } from "@/lib/support-rules";
import { SupportComposer } from "../support-composer";
import { InboxRefresh } from "../inbox-refresh";
import { updateSupportThreadAction, resolveSupportDeliveryAction } from "../actions";

export default async function SupportConversationPage({ params }: { params: Promise<{ threadId: string }> }) {
  const actor = await requirePlatformAdmin(P.inboxRead);
  const { threadId } = await params;
  if (!/^[0-9a-f-]{36}$/i.test(threadId)) notFound();
  const detail = await getSupportThread(threadId).catch(error => { if (error.message.includes("could not be found")) notFound(); throw error; });
  const { thread, messages } = detail;
  const canManage = actor.permissions.includes(P.inboxManage), canReply = actor.permissions.includes(P.inboxReply);
  const config = canReply ? await getSupportEmailConfig().catch(() => null) : null;
  const email = config ? publicSupportEmailConfig(config) : null;
  const needsReview = messages.some(item => item.kind === "email_reply" && ["sending", "unknown"].includes(item.delivery_status));
  const reference = thread.id.slice(0, 8).toUpperCase();
  return <><nav aria-label="Breadcrumb" className="text-xs text-zinc-500"><Link href="/admin/inbox">Inbox</Link> / {reference}</nav><AdminPageHeader eyebrow="Customer support" title={thread.customer_name}>#{reference} · {thread.customer_email}</AdminPageHeader><div className="mt-4 flex flex-wrap items-center gap-3"><StatusBadge value={thread.status} /><InboxRefresh /><Link href="/admin/inbox" className="text-sm text-orange-700">Back to inbox →</Link><a href={supportMailto(thread.customer_email, reference)} className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm">Open email ↗</a></div>
    <div className="mt-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="min-w-0"><AdminSection title="Customer message"><article className="rounded-xl border border-zinc-200 bg-white p-5"><p className="text-xs text-zinc-500">{thread.customer_name} · {formatAdminDateTime(thread.created_at)}</p><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-relaxed">{thread.message}</p></article></AdminSection>
      <AdminSection title="Conversation history">{messages.length ? <div className="grid gap-3">{messages.map(message => <article key={message.id} className={`rounded-xl border p-5 ${message.kind === "note" ? "border-amber-200 bg-amber-50" : "border-zinc-200 bg-white"}`}><div className="flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">{message.kind === "note" ? "Internal note" : message.kind === "manual_reply" ? "Reply recorded outside Reylumi" : "Email reply"}</h3><StatusBadge value={message.delivery_status === "sent" ? "accepted_by_email_service" : message.delivery_status} /></div><p className="mt-2 text-xs text-zinc-500">{message.actor_name || "Admin"} · {formatAdminDateTime(message.created_at)}{message.recipient_email ? ` · To ${message.recipient_email}` : ""}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed">{message.body}</p>{message.failure_reason && <p className="mt-3 text-xs text-red-700">{message.failure_reason}</p>}{message.provider_message_id && <p className="mt-2 break-all text-xs text-zinc-500">Email reference: {message.provider_message_id}</p>}
        {canReply && message.kind === "email_reply" && ["sending", "unknown"].includes(message.delivery_status) && <details className="mt-4 text-sm"><summary className="cursor-pointer font-medium text-orange-700">Review unconfirmed delivery</summary><p className="my-3 text-xs text-zinc-500">Check the email provider delivery logs first. This records the outcome and never resends the email. A send still in progress cannot be reviewed within its first two minutes.</p><AdminActionForm action={resolveSupportDeliveryAction} confirmMessage="Have you checked the email provider and confirmed this delivery outcome?" className="grid gap-3"><input type="hidden" name="message_id" value={message.id} /><label className="grid gap-1">Confirmed outcome<select name="outcome" className="rounded-lg border border-zinc-300 bg-white p-2"><option value="sent">Accepted by email service</option><option value="failed">Not sent</option></select></label><label className="grid gap-1">Review reason<textarea name="reason" required maxLength={500} className="rounded-lg border border-zinc-300 bg-white p-2" /></label><button className="justify-self-start rounded-lg border bg-white px-3 py-2">Record delivery review</button></AdminActionForm></details>}
      </article>)}</div> : <p className="text-sm text-zinc-500">No replies or internal notes yet.</p>}</AdminSection>
      {(canManage || canReply) && <AdminSection title="Follow up">{canReply && (!config || !supportEmailReady(config)) && <p className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Direct email is not connected. A platform owner can connect {SUPPORT_EMAIL} in <Link href="/admin/settings/support-email" className="underline">Email settings</Link>. You can use Open email and record your reply below.</p>}<SupportComposer threadId={thread.id} recipient={thread.customer_email} from={email?.from ?? SUPPORT_EMAIL} emailReady={Boolean(config && supportEmailReady(config))} canReply={canReply} canManage={canManage} blocked={needsReview || thread.status === "spam"} /></AdminSection>}
    </div><aside><AdminSection title="Handling"><p className="mb-4 text-sm text-zinc-500">{detail.assignee ? `Assigned to ${detail.assignee}` : "Unassigned"}</p>{canManage ? <AdminActionForm action={updateSupportThreadAction} className="grid gap-4"><input type="hidden" name="thread_id" value={thread.id} /><label className="grid gap-1.5 text-sm font-medium">Status<select name="status" defaultValue={thread.status} className="rounded-lg border border-zinc-300 bg-white px-3 py-2">{SUPPORT_STATUSES.map(status => <option key={status} value={status}>{SUPPORT_STATUS_LABELS[status]}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Assignment<select name="assignment" className="rounded-lg border border-zinc-300 bg-white px-3 py-2"><option value="keep">Keep current assignment</option><option value="me">Assign to me</option><option value="unassign">Unassign</option></select></label><button className="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Save handling</button></AdminActionForm> : <p className="text-sm text-zinc-500">Your role has read-only access.</p>}</AdminSection><AdminSection title="Contact"><p className="text-sm font-medium">{thread.customer_name}</p><a className="mt-2 block break-all text-sm text-orange-700" href={supportMailto(thread.customer_email, reference)}>{thread.customer_email}</a><p className="mt-3 text-xs text-zinc-500">Received {formatAdminDateTime(thread.created_at)}</p><p className="mt-2 text-xs text-zinc-500">Updated {formatAdminDateTime(thread.updated_at)}</p><p className="mt-4 text-xs leading-relaxed text-zinc-500">Replies received by your support email mailbox are not automatically imported here. This Inbox receives website form submissions.</p></AdminSection></aside></div>
  </>;
}
