import Link from "next/link";
import { getAdminNewAccounts, type RecentAdminRecord } from "@/lib/platform-admin/attention";
import { PLATFORM_ADMIN_PERMISSIONS as P, type PlatformAdminPermission } from "@/types/platform-admin";
import { loadOptionalAdminSection, SectionError } from "../_components/optional-section";
import { AccountRowActions } from "./account-row-actions";
export async function DashboardNewAccounts({ permissions }: { permissions: PlatformAdminPermission[] }) {
  const result = await loadOptionalAdminSection(getAdminNewAccounts);
  if (result.error) return <SectionError message={result.error} />;
  function section(kind: "user" | "location", records: RecentAdminRecord[], count: number) {
    const users = kind === "user";
    return <section aria-labelledby={`dashboard-new-${kind}`}><div className="dashboard-section-heading"><h2 id={`dashboard-new-${kind}`}>{users ? "Newest users" : "Newest salons"}</h2><Link className="dashboard-link" href={users ? "/admin/users?sort=created_desc" : "/admin/locations"}>View all {users ? "users" : "salons"} →</Link></div><p className="dashboard-list-description"><strong>{count.toLocaleString("en-US")}</strong> new {users ? "accounts" : "salons"} today · CT</p>{records.length ? <ul className="dashboard-new-list">{records.map(record => <li key={record.id} className="dashboard-new-row"><div className="dashboard-new-record"><Link className="dashboard-record-avatar" aria-label={`Open ${record.name}`} href={`/admin/${users ? "users" : "locations"}/${record.id}`}>{record.name.slice(0, 1).toUpperCase()}</Link><div className="dashboard-record-name"><Link href={`/admin/${users ? "users" : "locations"}/${record.id}`}><strong>{record.name}</strong></Link>{users ? <small>{permissions.includes(P.usersReadSensitive) ? record.contact || "No email or phone recorded" : "Contact restricted by your role"} · <span className={`dashboard-status status-${record.status}`}>{record.status.replaceAll("_", " ")}</span></small> : <><small>{record.address || "Address not recorded"} · <span className={`dashboard-status status-${record.status}`}>{record.status.replaceAll("_", " ")}</span></small><small>Created by: {record.creator_id ? <Link className="dashboard-link" href={`/admin/users/${record.creator_id}`}>{record.creator_name || "Unnamed user"}{record.creator_contact ? ` · ${record.creator_contact}` : ""}</Link> : "Not recorded"}</small></>}</div><time dateTime={record.created_at}>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/Chicago" }).format(new Date(record.created_at))} CT</time></div><AccountRowActions id={record.id} name={record.name} kind={kind} status={record.status} marked={record.marked} permissions={permissions} /></li>)}</ul> : <p className="dashboard-muted">No {users ? "accounts" : "salons"} yet.</p>}</section>;
  }
  return <div className="dashboard-new-accounts">{permissions.includes(P.usersRead) && section("user", result.data?.users ?? [], result.data?.users_today ?? 0)}{permissions.includes(P.locationsRead) && section("location", result.data?.salons ?? [], result.data?.salons_today ?? 0)}</div>;
}
